WTF_CSRF_ENABLED = False
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SECRET_KEY = 'A0Zr98j/3yX R~XHH!jmN]LWX/,?RT'

MAIL_SERVER = 'smtp.googlemail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = 'testapp545545'
MAIL_PASSWORD = 'January28'
